#
# Your Crowdin credentials
#
"project_id": "1"
"api_token": "CROWDIN_TOKEN"
"base_path": "."
"base_url": "https://solana.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
    {
      #
      # Source files filter
      # e.g. "/resources/en/*.json"
      #
      "source": "/public/locales/en/common.json",

      #
      # Where translations will be placed
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
      "translation": "/public/locales/%two_letters_code%/common.json",
    },
    # {
    #   "source": "/content/**/*.mdx",
    #   "translation": "/content/**/%file_name%.%two_letters_code%.mdx",
    # },
    # {
    #   "source": "/content/**/meta.json",
    #   "translation": "/content/**/%file_name%.%two_letters_code%.json",
    # },
    {
      "source": "/content/docs/intro/**/*.mdx",
      "translation": "/content/docs/intro/**/%file_name%.%two_letters_code%.mdx",
      "skip_untranslated_files": true,
    },
    {
      "source": "/content/docs/intro/**/meta.json",
      "translation": "/content/docs/intro/**/%file_name%.%two_letters_code%.json",
      "skip_untranslated_files": true,
    },
  ]
