#
# Your Crowdin credentials
#
"project_id": "1"
"api_token": "CROWDIN_TOKEN"
"base_path": "."
"base_url": "https://solana.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
    {
      #
      # Source files filter
      # e.g. "/resources/en/*.json"
      #
      "source": "/public/locales/en/common.json",

      #
      # Where translations will be placed
      # e.g. "/resources/%two_letters_code%/%original_file_name%"
      #
      "translation": "/public/locales/%two_letters_code%/common.json",
    },
  ]
