import type { AgendaItem } from "@/content/agenda/types";

export const fallbackAgenda = [
  {
    day: "Day 1",
    description:
      "Netus mi euismod vitae praesent neque non eu. Aliquam dui ut nulla turpis senectus. Blandit sit consequat rhoncus in risus vulputate massa ultrices. Montes nulla amet diam semper lacinia sit enim. Neque nunc pellentesque sit praesent vitae. A consectetur eu nibh velit nunc amet dui bibendum facilisi.",
    duration: "15 min.",
    id: "fallback-what-to-expect",
    location: "Main Stage",
    sortOrder: 0,
    speakers: [
      {
        company: "Solana Foundation",
        name: "Lily Liu",
        title: "President",
      },
      {
        company: "Solana Foundation",
        name: "Akshay BD",
        title: "Non-CMO",
      },
    ],
    tag: "Keynote",
    time: "09:00",
    title: "What to Expect at Breakpoint 2026",
  },
  {
    day: "Day 1",
    duration: "15 min.",
    id: "fallback-opening-keynote",
    location: "Main Stage",
    sortOrder: 1,
    speakers: [],
    tag: "Keynote",
    time: "09:30",
    title: "Opening Keynote & Macro Teach-In",
  },
  {
    day: "Day 1",
    duration: "25 min.",
    id: "fallback-galaxy-helius",
    location: "Main Stage",
    sortOrder: 2,
    speakers: [],
    tag: "Fireside",
    time: "09:45",
    title: "Galaxy's Mike Novogratz and Helius' Mert Mumtaz",
  },
  {
    day: "Day 1",
    duration: "45 min.",
    id: "fallback-state-network",
    location: "Main Stage",
    sortOrder: 3,
    speakers: [],
    tag: "Keynote",
    time: "10:05",
    title: "The State of the Network",
  },
  {
    day: "Day 1",
    duration: "30 min.",
    id: "fallback-institutional-staking",
    location: "Main Stage",
    sortOrder: 4,
    speakers: [],
    tag: "Fireside",
    time: "10:35",
    title: "Institutional-Grade Staking in ETFs With Helius and Bitwise",
  },
  {
    day: "Day 1",
    duration: "45 min.",
    id: "fallback-political-alignment",
    location: "Main Stage",
    sortOrder: 5,
    speakers: [],
    tag: "Debate",
    time: "11:05",
    title:
      "This House rejects political alignment as a growth strategy for crypto.",
  },
  {
    day: "Day 1",
    duration: "7 min.",
    id: "fallback-state-returns",
    location: "Main Stage",
    sortOrder: 6,
    speakers: [],
    tag: "Keynote",
    time: "11:50",
    title: "The State of Returns on Solana",
  },
  {
    day: "Day 1",
    duration: "15 min.",
    id: "fallback-raoul-pal",
    location: "Main Stage",
    sortOrder: 7,
    speakers: [],
    tag: "Keynote",
    time: "11:57",
    title: "EXPAAM's Raoul Pal",
  },
  {
    day: "Day 1",
    duration: "25 min.",
    id: "fallback-income-strategies",
    location: "Main Stage",
    sortOrder: 8,
    speakers: [],
    tag: "Fireside",
    time: "13:15",
    title: "Income Generating Strategies in Crypto: Real World Examples",
  },
  {
    day: "Day 1",
    duration: "1hr 30m",
    id: "fallback-lunch",
    sortOrder: 9,
    speakers: [],
    time: "13:40",
    title: "Lunch Break",
    variant: "static",
  },
  {
    day: "Day 1",
    duration: "15 min.",
    id: "fallback-one-chain",
    location: "Main Stage",
    sortOrder: 10,
    speakers: [],
    tag: "Debate",
    time: "15:00",
    title:
      "One Chain to Rule Them All: Can Solana Alone Support Wall Street's Demands?",
  },
  {
    day: "Day 1",
    duration: "20 min.",
    id: "fallback-mainstream",
    location: "Main Stage",
    sortOrder: 11,
    speakers: [],
    tag: "Keynote",
    time: "15:15",
    title: "An Institutional Perspective: Solana Goes Mainstream",
  },
  {
    day: "Day 1",
    duration: "20 min.",
    id: "fallback-dats",
    location: "Main Stage",
    sortOrder: 12,
    speakers: [],
    tag: "Keynote",
    time: "15:35",
    title: "DATs: Why DATs Will Succeed - and Why They Won't",
  },
  {
    day: "Day 1",
    duration: "30 min.",
    id: "fallback-wall-street-metrics",
    location: "Main Stage",
    sortOrder: 13,
    speakers: [],
    tag: "Fireside",
    time: "15:55",
    title: "What Wall Street Wants: Metrics That Matter",
  },
] satisfies AgendaItem[];
