// Tailwind-only bridge for older solana-lib landing sections. The page components
// keep their existing content and order while sharing the current site palette.
export const legacyLandingTheme = [
  "bg-black text-white font-brand",
  "[&_.tw-switchback-gradient]:!bg-none",
  "[&_section]:!max-w-[1440px] [&_section]:!px-5 md:[&_section]:!px-8 xl:[&_section]:!px-10",
  "[&_section]:!py-16 md:[&_section]:!py-24 xl:[&_section]:!py-32",
  "[&_h1]:!font-brand [&_h1]:!font-medium [&_h1]:!leading-[1.05] [&_h1]:!tracking-[-0.05em] [&_h1]:!text-5xl md:[&_h1]:!text-7xl xl:[&_h1]:!text-[88px]",
  "[&_h2]:!font-brand [&_h2]:!font-medium [&_h2]:!leading-[1.1] [&_h2]:!tracking-[-0.04em] [&_h2]:!text-4xl md:[&_h2]:!text-5xl xl:[&_h2]:!text-6xl",
  "[&_h3]:!font-brand [&_h3]:!font-medium [&_h3]:!tracking-[-0.025em] [&_h3]:!text-white [&_h3]:!text-2xl md:[&_h3]:!text-3xl",
  "[&_.tw-eyebrow]:!font-brand-mono [&_.tw-eyebrow]:!text-xs [&_.tw-eyebrow]:!tracking-[0.12em] [&_.tw-eyebrow]:!text-[#CA9FF5]",
  "[&_.tw-text-body]:!text-[#ABABBA] [&_.tw-text-body]:!leading-relaxed",
  "[&_p]:!leading-relaxed",
  "[&_.tw-bg-gray-900]:!bg-[#111114] [&_.tw-bg-gray-800]:!bg-[#111114]",
  "[&_.tw-bg-gradient-black-blue]:!bg-none [&_.tw-bg-gradient-black-blue]:!bg-[#111114]",
  "[&_.tw-bg-gradient-black-purple]:!bg-none [&_.tw-bg-gradient-black-purple]:!bg-[#111114]",
  "[&_.tw-border-gradient]:!border-white/10 [&_.tw-card]:!border-white/10",
  "[&_.tw-border-b-purple-400]:!border-white/10 [&_.tw-border-b-blue-100]:!border-white/10 [&_.tw-border-b-lightPurple-100]:!border-white/10",
  "[&_.tw-rounded-2xl]:!rounded-3xl",
  "[&_.tw-bg-gradient-button]:!bg-none [&_.tw-bg-gradient-button]:!bg-white [&_.tw-bg-gradient-button]:!text-black",
  "[&_a.tw-bg-purple-500]:!bg-white [&_a.tw-bg-purple-500]:!text-black",
  "[&_a.tw-border]:!border-white/50 [&_a.tw-border]:!text-white",
  "[&_button.tw-border]:!border-white/50 [&_button.tw-border]:!text-white",
  "[&_.tw-rounded-full]:!font-brand-mono [&_.tw-rounded-full]:!text-xs [&_.tw-rounded-full]:!tracking-[0.08em]",
  "[&_a]:focus-visible:!outline [&_a]:focus-visible:!outline-2 [&_a]:focus-visible:!outline-offset-4 [&_a]:focus-visible:!outline-[#CA9FF5]",
  "[&_button]:focus-visible:!outline [&_button]:focus-visible:!outline-2 [&_button]:focus-visible:!outline-offset-4 [&_button]:focus-visible:!outline-[#CA9FF5]",
].join(" ");
