import type { BreakpointSpeaker } from "@/content/speakers/types";

export const fallbackSpeakers = [
  {
    company: "Bybit",
    id: "fallback-alexandra-nadel",
    name: "Alexandra Nadel",
    role: "Associate Director, Business Development, Onchain Solutions",
    slug: "alexandra-nadel",
    sortOrder: 0,
  },
  {
    company: "Anza",
    id: "fallback-alexander-meissner",
    name: "Alexander Meißner",
    role: "SVM Team Lead",
    slug: "alexander-meissner",
    sortOrder: 1,
    xUrl: "https://x.com/solana",
  },
  {
    company: "Abra",
    id: "fallback-bill-barhydt",
    name: "Bill Barhydt",
    role: "CEO",
    slug: "bill-barhydt",
    sortOrder: 2,
  },
  {
    company: "Drift",
    id: "fallback-bin-chen",
    name: "Bin Chen",
    role: "Co-Founder",
    slug: "bin-chen",
    sortOrder: 3,
    xUrl: "https://x.com/solana",
  },
  {
    company: "Electric Capital",
    id: "fallback-emily-meyers",
    name: "Emily Meyers",
    role: "General Counsel",
    slug: "emily-meyers",
    sortOrder: 4,
    xUrl: "https://x.com/solana",
  },
  {
    company: "21.co",
    id: "fallback-hany-rashwan",
    name: "Hany Rashwan",
    role: "CEO",
    slug: "hany-rashwan",
    sortOrder: 5,
    xUrl: "https://x.com/solana",
  },
  {
    company: "Circle",
    id: "fallback-jeremy-allaire",
    name: "Jeremy Allaire",
    role: "Chairman & CEO",
    slug: "jeremy-allaire",
    sortOrder: 6,
  },
  {
    company: "Oinkonomics",
    id: "fallback-kamel-ben-rhouma",
    name: "Kamel Ben Rhouma",
    role: "Main Developer",
    slug: "kamel-ben-rhouma",
    sortOrder: 7,
  },
  {
    id: "fallback-kari-aka-bangerz",
    name: "Kari aka Bangerz",
    role: "Creator",
    slug: "kari-aka-bangerz",
    sortOrder: 8,
    xUrl: "https://x.com/solana",
  },
  {
    company: "Gameshift",
    id: "fallback-karthik-makayee",
    name: "Karthik Makayee",
    role: "Co-Founder",
    slug: "karthik-makayee",
    sortOrder: 9,
  },
  {
    company: "Chomp",
    id: "fallback-kiko-zang",
    name: "Kiko Zang",
    role: "Co-Founder",
    slug: "kiko-zang",
    sortOrder: 10,
    xUrl: "https://x.com/solana",
  },
] satisfies BreakpointSpeaker[];
