import { defaultLocale } from "@workspace/i18n/config";
import { LoaderConfig, LoaderOutput } from "fumadocs-core/source";

// remove extra params generated by fumadocs i18n
export function toStaticParams(source: LoaderOutput<LoaderConfig>) {
  return source.generateParams().filter(({ lang }) => lang === defaultLocale);
}

export function getUrlWithoutLocale(page: { url: string; locale?: string }) {
  return toUrlWithoutLocale(page.url, page.locale ?? "en");
}

export function toUrlWithoutLocale(url: string, locale: string) {
  return url.replace(`/${locale}/`, "/");
}
