import { defaultLocale } from "@/i18n/config.cjs";
import { LoaderConfig, LoaderOutput, Page } from "fumadocs-core/source";

// remove extra params generated by fumadocs i18n
export function toStaticParams(source: LoaderOutput<LoaderConfig>) {
  return source.generateParams().filter(({ lang }) => lang === defaultLocale);
}

export function getUrlWithoutLocale(
  page: Page<LoaderConfig["source"]["pageData"]>,
) {
  return toUrlWithoutLocale(page.url, page.locale);
}

export function toUrlWithoutLocale(url: string, locale: string) {
  return url.replace(`/${locale}/`, "/");
}
