import type { NavTopLevelSectionMetadata } from "./nav-types";

export const HEADER_SECTION_METADATA: Array<
  Omit<NavTopLevelSectionMetadata, "mobileIcon" | "Content">
> = [
  {
    id: "use_solana",
    titleKey: "nav.useSolana.title",
    matchRules: [
      { type: "equals", value: "/use-solana" },
      { type: "equals", value: "/wallets" },
      { type: "equals", value: "/solana-wallets" },
      { type: "includes", value: "/learn" },
      { type: "equals", value: "/staking" },
      { type: "equals", value: "/solutions/consumer" },
    ],
    contentAlign: "left",
  },
  {
    id: "build",
    titleKey: "nav.build.title",
    matchRules: [
      { type: "includes", value: "/developers" },
      { type: "includes", value: "/docs" },
      { type: "equals", value: "/rpc" },
      { type: "equals", value: "/hackathon" },
      { type: "equals", value: "/solutions/payments-tooling" },
      { type: "equals", value: "/solutions/token-extensions" },
    ],
    contentAlign: "left",
  },
  {
    id: "enterprise",
    titleKey: "nav.enterprise.title",
    matchRules: [
      { type: "equals", value: "/enterprise" },
      { type: "equals", value: "/solutions" },
      { type: "equals", value: "/solutions/enterprise" },
      { type: "equals", value: "/solutions/institutional-payments" },
      { type: "equals", value: "/solutions/commerce-tooling" },
      { type: "equals", value: "/solutions/stablecoins" },
      { type: "equals", value: "/solutions/tokenization" },
      { type: "equals", value: "/solutions/real-world-assets" },
      { type: "equals", value: "/solutions/defi" },
      { type: "equals", value: "/solutions/financial-infrastructure" },
      { type: "equals", value: "/solutions/financial-institutions" },
      { type: "equals", value: "/privacy" },
    ],
    contentAlign: "left",
    contentClassName: "xl:overflow-y-auto xl:max-h-[90vh]",
  },
  {
    id: "products",
    titleKey: "nav.products.title",
    matchRules: [
      { type: "equals", value: "/products" },
      { type: "equals", value: "/solutions/sdp" },
      { type: "equals", value: "/solutions/ai" },
      { type: "equals", value: "/x402" },
      { type: "includes", value: "/x402/" },
      { type: "equals", value: "/agent-registry" },
      { type: "includes", value: "/agent-registry/" },
      { type: "equals", value: "/skills" },
      { type: "equals", value: "/solutions/actions" },
    ],
    contentAlign: "center",
  },
  {
    id: "ecosystem",
    titleKey: "nav.ecosystem.title",
    matchRules: [
      { type: "equals", value: "/ecosystem" },
      { type: "equals", value: "/network" },
      { type: "equals", value: "/validators" },
      { type: "equals", value: "/community" },
      { type: "includes", value: "/events" },
      { type: "equals", value: "/accelerate" },
      { type: "includes", value: "/accelerate/" },
      { type: "equals", value: "/breakpoint" },
      { type: "equals", value: "/news" },
      { type: "includes", value: "/podcasts" },
      { type: "equals", value: "/reports" },
      { type: "includes", value: "/reports/" },
      { type: "equals", value: "/research" },
      { type: "equals", value: "/solutions/depin" },
      { type: "equals", value: "/solutions/desci" },
      { type: "equals", value: "/solutions/btcfi" },
      { type: "equals", value: "/solutions/gaming-and-entertainment" },
      { type: "equals", value: "/solutions/artists-creators" },
      { type: "equals", value: "/solutions/request-for-startups" },
    ],
    contentAlign: "center",
    contentClassName: "xl:overflow-y-auto xl:max-h-[90vh]",
  },
];
