import { defineConfig } from "oxlint";

export const baseConfig = defineConfig({
  plugins: ["typescript"],
  categories: {
    correctness: "off",
  },
  env: {
    builtin: true,
  },
  ignorePatterns: [
    "**/node_modules/**",
    "**/.next/**",
    "**/.source/**",
    "**/.turbo/**",
    "**/coverage/**",
    "**/dist/**",
    "**/build/**",
    "**/public/**",
    "**/*.d.ts",
    "**/next-env.d.ts",
  ],
  rules: {
    "constructor-super": "warn",
    "for-direction": "warn",
    "getter-return": "warn",
    "no-async-promise-executor": "warn",
    "no-case-declarations": "warn",
    "no-class-assign": "warn",
    "no-compare-neg-zero": "warn",
    "no-cond-assign": "warn",
    "no-const-assign": "warn",
    "no-constant-binary-expression": "warn",
    "no-constant-condition": "warn",
    "no-control-regex": "warn",
    "no-debugger": "warn",
    "no-delete-var": "warn",
    "no-dupe-class-members": "warn",
    "no-dupe-else-if": "warn",
    "no-dupe-keys": "warn",
    "no-duplicate-case": "warn",
    "no-empty": "warn",
    "no-empty-character-class": "warn",
    "no-empty-pattern": "warn",
    "no-empty-static-block": "warn",
    "no-ex-assign": "warn",
    "no-extra-boolean-cast": "warn",
    "no-fallthrough": "warn",
    "no-func-assign": "warn",
    "no-global-assign": "warn",
    "no-import-assign": "warn",
    "no-invalid-regexp": "warn",
    "no-irregular-whitespace": "warn",
    "no-loss-of-precision": "warn",
    "no-misleading-character-class": "warn",
    "no-new-native-nonconstructor": "warn",
    "no-nonoctal-decimal-escape": "warn",
    "no-obj-calls": "warn",
    "no-prototype-builtins": "warn",
    "no-redeclare": "warn",
    "no-regex-spaces": "warn",
    "no-self-assign": "warn",
    "no-setter-return": "warn",
    "no-shadow-restricted-names": "warn",
    "no-sparse-arrays": "warn",
    "no-this-before-super": "warn",
    "no-unreachable": "warn",
    "no-unsafe-finally": "warn",
    "no-unsafe-negation": "warn",
    "no-unsafe-optional-chaining": "warn",
    "no-unused-labels": "warn",
    "no-unused-private-class-members": "warn",
    "no-unused-vars": "warn",
    "no-useless-backreference": "warn",
    "no-useless-catch": "warn",
    "no-useless-escape": "warn",
    "no-with": "warn",
    "require-yield": "warn",
    "use-isnan": "warn",
    "valid-typeof": "warn",
    "no-array-constructor": "warn",
    "no-unused-expressions": "warn",
    "typescript/ban-ts-comment": "warn",
    "typescript/no-duplicate-enum-values": "warn",
    "typescript/no-empty-object-type": "warn",
    "typescript/no-explicit-any": "warn",
    "typescript/no-extra-non-null-assertion": "warn",
    "typescript/no-misused-new": "warn",
    "typescript/no-namespace": "warn",
    "typescript/no-non-null-asserted-optional-chain": "warn",
    "typescript/no-require-imports": "warn",
    "typescript/no-this-alias": "warn",
    "typescript/no-unnecessary-type-constraint": "warn",
    "typescript/no-unsafe-declaration-merging": "warn",
    "typescript/no-unsafe-function-type": "warn",
    "typescript/no-wrapper-object-types": "warn",
    "typescript/prefer-as-const": "warn",
    "typescript/prefer-namespace-keyword": "warn",
    "typescript/triple-slash-reference": "warn",
  },
  overrides: [
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "warn",
        "no-with": "off",
        "prefer-const": "warn",
        "prefer-rest-params": "warn",
        "prefer-spread": "warn",
      },
    },
    {
      files: ["**/__tests__/**/*.{ts,tsx}", "**/*.{test,spec}.{ts,tsx}"],
      rules: {
        "typescript/no-explicit-any": "off",
      },
    },
  ],
});
