name: node_js
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Format:
    name: Test formatting...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: before_install
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: installing_yarn
        run: yarn install
      - name: formatting
        run: yarn format:check
  stage:
    name: Test linting...
    needs: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: before_install
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: installing_yarn & lint
        run: |
          yarn install
          yarn lint
