name: node_js
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Set fs.inotify
        run: sudo sysctl -w fs.inotify.max_user_watches=524288
      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm exec prettier --ignore-path .prettierignore --check .

  lint-apps:
    name: Lint App - ${{ matrix.workspace }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - solana-com
          - solana-com-accelerate
          - solana-com-breakpoint
          - solana-com-media
          - solana-docs
          - solana-templates
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Set fs.inotify
        run: sudo sysctl -w fs.inotify.max_user_watches=524288
      - name: Install dependencies
        run: pnpm install
      - name: Lint workspace
        run: pnpm --filter ${{ matrix.workspace }} lint

  lint-packages:
    name: Lint Package - ${{ matrix.workspace }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - "@solana-com/ui-chrome"
          - "@workspace/ecosystem-data"
          - "@workspace/i18n"
          - "@workspace/sentry"
          - "@workspace/ui"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Set fs.inotify
        run: sudo sysctl -w fs.inotify.max_user_watches=524288
      - name: Install dependencies
        run: pnpm install
      - name: Lint workspace
        run: pnpm --filter ${{ matrix.workspace }} lint
