name: Generate LLMs.txt

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    # Run every 7 days at 2:03 AM UTC
    - cron: '3 2 */7 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-llms-txt:
    name: Generate LLMs.txt file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate LLMs.txt
        run: |
          python llmtxt-generator.py
          echo "LLMs.txt file generated"

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet LLMs.txt || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          commit-message: "Update LLMs.txt via automated workflow"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: "automated-llms-txt-update"
          delete-branch: true
          title: "Update LLMs.txt file"
          body: |
            This PR updates the LLMs.txt file with the latest documentation structure.
            
            - Automatically generated by the Generate LLMs.txt workflow
            - Updates reflect current documentation structure
          labels: "documentation, automated"
          draft: false
