name: Test formatting

on:
  pull_request:
    branches: [ main ]

jobs:
  test-formatting:
    name: Test formatting...
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Increase file watchers
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      
    - name: Install dependencies
      run: yarn install
      
    - name: Check formatting
      run: yarn format:check